const TrackerTypes = {
	ADD_TRACKER: 'ADD_TRACKER',
	REMOVE_TRACKER: 'REMOVE_TRACKER',
	PAUSE_TOGGLE: 'PAUSE_TOGGLE',
	FETCH_TRACKERS: 'FETCH_TRACKERS',
	MODIFY_TRACKER: 'MODIFY_TRACKER'
};

export default TrackerTypes;